version: "3.9"

x-logs: &logs
  logging:
    driver: "json-file"
    options:
      max-size: "100m"
      max-file: "10"
      tag: "{{.ImageName}}|{{.Name}}"

x-common: &common
  <<: *logs
  restart: unless-stopped

services:
  app_python:
    image: bragov4ik/time_web_app:latest
    ports:
      - 80:8000
    command: [ "-b", "0.0.0.0:8000", "--log-level", "debug" ]
    <<: *common
    restart: always
  
  app_rust:
    image: bragov4ik/time_rust_web_app:latest
    ports:
      - 81:8000
    environment:
      ROCKET_LOG_LEVEL: "normal"
    <<: *common
    restart: always

  loki:
    image: grafana/loki:2.6.1
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    <<: *common

  promtail:
    image: grafana/promtail:2.6.1
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - promtail-data:/var/lib/promtail/positions
      - ${PWD}/promtail.yml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml
    <<: *common

  grafana:
    image: grafana/grafana:latest
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
    volumes:
      - grafana-data:/var/lib/grafana
      - ${PWD}/grafana/provisioning:/etc/grafana/provisioning
    entrypoint:
      - sh
      - -euc
      - |
        mkdir -p /etc/grafana/provisioning/datasources
        cat <<EOF > /etc/grafana/provisioning/datasources/ds.yaml
        apiVersion: 1
        datasources:
          - name: Loki
            type: loki
            access: proxy
            url: http://loki:3100
          - name: Prometheus
            type: prometheus
            access: proxy
            url: http://prometheus:9090
        EOF
        /run.sh
    ports:
      - "3000:3000"
    <<: *common
  
  prometheus:
    image: prom/prometheus:v2.39.1
    volumes:
      - ${PWD}/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=14d'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - "9090:9090"
    <<: *common

volumes:
  promtail-data: {}
  prometheus-data: {}
  grafana-data: {}