apiVersion: v1
kind: Service
metadata:
  name: python-time-app-service
spec:
  selector:
    app: time-webapp-python
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer