apiVersion: v1
kind: Service
metadata:
  name: rust-time-app-service
spec:
  selector:
    app: time-webapp-rust
  ports:
    - protocol: TCP
      port: 81
      targetPort: 8000
  type: LoadBalancer