apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "time-web-app-rust.fullname" . }}-config
  labels:
    {{- include "time-web-app-rust.labels" . | nindent 4 }}
data:
  config.json: |-
    {{ .Files.Get "files/config.json" }}
