name: Docker release

# Trigger on any tag that is a semver version
on:
  workflow_call:
    inputs:
      image_tag:
        required: true
        type: string
      docker_repo_name:
        required: true
        type: string
      project_folder:
        required: true
        type: string
      publish:
        required: true
        type: boolean

permissions:
  contents: read

jobs:
  docker-publish:

    runs-on: ubuntu-latest
    timeout-minutes: 40
    
    steps:
      # `docker/build-push-action` can work without checking out repo first
      # https://github.com/docker/build-push-action#git-context
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      # Publish image with tag extracted from the `version-extractor` step and
      # update latest version
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: "{{defaultContext}}:app_python"
          push: ${{ inputs:publish }}
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/${{ inputs.docker_repo_name }}:latest,
            ${{ secrets.DOCKER_HUB_USERNAME }}/${{ inputs.docker_repo_name }}:${{ inputs.image_tag }}
          cache-from: type=gha
          cache-to: type=gha,mode=max