name: Docker release

# Trigger on any tag that is a semver version
on:
  workflow_call:
    inputs:
      docker_repo_name:
        required: true
        type: string
      project_folder:
        required: true
        type: string

permissions:
  contents: read

jobs:
  docker-publish:

    runs-on: ubuntu-latest
    timeout-minutes: 40
    
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      # `docker/build-push-action` can work without checking out repo first
      # https://github.com/docker/build-push-action#git-context
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/${{ inputs.docker_repo_name }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
      # Publish image with tag extracted from the `version-extractor` step and
      # update latest version
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ${{ inputs.project_folder }}
          file: ${{ inputs.project_folder }}/Dockerfile
          push: ${{ startsWith(github.ref, 'refs/tags') }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max