name: Lint markdown files

on:
  pull_request:
    branches:
      - master

permissions:
  contents: read

jobs:

  lint-changelog:
    name: Lint markdown

    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Lint changelog file
      uses: docker://avtodev/markdown-lint:v1 # fastest way
      with:
        args: '**/*.md'
