name: Python package

on:
  push:
    branches:
      - 'lab*'
      - master
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    # To avoid multiple runs on single commit
    - name: Exit if it's a pull request from 'lab*' to master
      if: endsWith(github.ref, 'lab*') == true && endsWith(github.base_ref, 'master')
      run: exit -1
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        # Not explicitly choosing requirements so that we won't break
        # everything if we change/restructure them it later
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements/*.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r app_python/requirements/test.txt
    - name: Lint with black
      uses: psf/black@stable
      with:
        options: "--check --verbose"
        src: "app_python/src"
    - name: Test with pytest
      run: |
        pytest