name: Python release

# Trigger on any tag that is a semver version
on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+

jobs:
  docker-publish:

    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout 
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Prepare tag number
        run: echo ::set-output name=VERSION::${GITHUB_REF#*/*/v}
        id: version-extractor
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/time_web_app:latest,
            ${{ secrets.DOCKER_HUB_USERNAME }}/time_web_app:${{ steps.version-extractor.outputs.VERSION }}