name: Python package

on:
  push:
    branches:
      - 'lab*'
      - master
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r app_python/requirements/test.txt
    - name: Lint with black
      uses: psf/black@stable
      with:
        options: "--check --verbose"
        src: "app_python/src"
    - name: Test with pytest
      run: |
        pytest