name: Python release

# Trigger on any tag that is a semver version
on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+

permissions:
  contents: read

jobs:
  docker-publish:

    runs-on: ubuntu-latest
    timeout-minutes: 40
    
    steps:
      # `docker/build-push-action` can work without checking out repo first
      # https://github.com/docker/build-push-action#git-context
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      # We extract only version numbers from tag
      # refs/tag/v1.2.3 -> 1.2.3
      # The pattern should be correct since we've already filtered tag
      # with 'on' trigger
      - name: Prepare tag number
        run: echo ::set-output name=VERSION::${GITHUB_REF#*/*/v}
        id: version-extractor
      # Publish image with tag extracted from the `version-extractor` step and
      # update latest version
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: "{{defaultContext}}:app_python"
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/time_web_app:latest,
            ${{ secrets.DOCKER_HUB_USERNAME }}/time_web_app:${{ steps.version-extractor.outputs.VERSION }}