name: Rust

on:
  push:
    branches:
      - 'lab*'
      - $default-branch
    paths:
      - 'app_rust/**'
      - '.github/**'
  pull_request:
    branches:
      - $default-branch 
    paths:
      - 'app_rust/**'
      - '.github/**'

env:
  CARGO_TERM_COLOR: always

permissions:
  contents: read
  security-events: write

jobs:
  checks:

    # To avoid multiple runs on single commit
    # It is still checked by push trigger, so no worries.
    if: "!(contains(github.head_ref, 'lab') == true && endsWith(github.base_ref, 'master'))"
    timeout-minutes: 30
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./app_rust

    steps:
    - uses: actions/checkout@v3
    # https://github.com/actions/cache/blob/main/examples.md#rust---cargo
    - name: Cache dependencies & build artifacts
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          ./target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - name: Code style check
      run: cargo fmt --all --verbose --check
    - name: Build
      run: cargo check
    - name: Run tests
      run: cargo test --verbose
    - run: rustup component add clippy
    - name: Run clippy check
      run: cargo clippy --all-features -- -D warnings
