name: Security audit

on:
  push:
    paths: 
      - '**/Cargo.toml'
      - '**/Cargo.lock'

defaults:
  run:
    working-directory: ./app_rust

permissions:
  contents: read

jobs:
  security_audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/audit-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}