name: Rust release

# Trigger on any tag that is a semver version
on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+

permissions:
  contents: read

env:
  DOCKER_REPO_NAME: time_rust_web_app

jobs:
  docker-publish:

    runs-on: ubuntu-latest
    timeout-minutes: 40
    
    steps:
      # We extract only version numbers from tag
      # refs/tag/v1.2.3 -> 1.2.3
      # The pattern should be correct since we've already filtered tag
      # with 'on' trigger
      - name: Prepare tag number
        run: echo ::set-output name=VERSION::${GITHUB_REF#*/*/v}
        id: version-extractor
      - uses: ./.github/workflows/docker-release.yml
        secrets: inherit
        with:
          image_tag: ${{ steps.version-extractor.outputs.VERSION }}
          docker_repo_name: ${{ env.DOCKER_REPO_NAME }}
          project_folder: app_rust